# Generated by Django 5.1 on 2024-08-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='entry_time',
        ),
    ]
